spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/moviedb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
